ERROR:TeleBot:ReadTimeout occurred, args=(ReadTimeoutError("HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)",),)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/telebot/util.py", line 59, in run
    task(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telebot/__init__.py", line 158, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/telebot/__init__.py", line 128, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/usr/local/lib/python2.7/dist-packages/telebot/apihelper.py", line 180, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/usr/local/lib/python2.7/dist-packages/telebot/apihelper.py", line 54, in _make_request
    timeout=(connect_timeout, read_timeout), proxies=proxy)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)

INFO:root:HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)
INFO:root:(sendCards)User id: 259522004
Response: A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:
[{"ok":false,"error_code":403,"description":"Forbidden: bot was blocked by the user"}]
INFO:root:(sendCards)User id: 259522004
Response: A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:
[{"ok":false,"error_code":403,"description":"Forbidden: bot was blocked by the user"}]
INFO:root:(sendCards)User id: 259522004
Response: A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:
[{"ok":false,"error_code":403,"description":"Forbidden: bot was blocked by the user"}]
INFO:root:(sendCards)User id: 259522004
Response: A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:
[{"ok":false,"error_code":403,"description":"Forbidden: bot was blocked by the user"}]
